import { existsSync, mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { RETIRED_SKILL_IDS } from "../src/external-assets.js";
import { runInstall } from "../src/installer.js";
import type { InstallSpec, OptionFlags, Track } from "../src/types.js";

const HARNESS_ROOT = resolve(__dirname, "..");

const NO_OPTS: OptionFlags = {
  withCodexTrust: false,
};

function buildSpec(tracks: Track[], projectDir: string): InstallSpec {
  return {
    tracks,
    options: NO_OPTS,
    cli: ["claude"],
    projectDir,
  };
}

/** No-op external install — tests don't want to trigger real `claude plugin install`. */
const NO_EXTERNAL = null;

const TRACKS: ReadonlyArray<Track> = [
  "base",
  "tooling",
  "csr-supabase",
  "csr-fastify",
  "csr-fastapi",
  "ssr-htmx",
  "ssr-nextjs",
  "data",
  "executive",
  "full",
  "project-management",
  "growth-marketing",
];

/**
 * Per-track expected files (subset — proves Track-pattern routing in manifest.ts).
 *
 * 2026-08-02 정비 — 기술스택 상세 룰 8종이 배포에서 빠졌다.
 * 2026-08-12 — `playwright-launch` 가 스킬로 흡수돼 **UI 트랙 전용 룰 축이 없어졌다.** 남은
 * 라우팅 축은 dev 룰(test-policy·ship-checklist = executive 제외) · tooling/full 의
 * cli-development · MCP 매핑 셋이다. UI 트랙 행은 그래서 dev 룰 + MCP 로 구분을 증명한다 —
 * 전 트랙 공통 룰만 적으면 이 표가 라우팅을 더 이상 증명하지 못한다.
 */
const TRACK_EXPECTATIONS: Record<Track, { rules: string[]; mcp?: string[] }> = {
  // #456 — dev 룰은 받되 cli-development 는 없다 (tooling 과의 차이가 곧 base 의 정의)
  base: { rules: ["test-policy", "ship-checklist"] },
  tooling: { rules: ["cli-development", "test-policy"] },
  "csr-supabase": { rules: ["test-policy"], mcp: ["supabase"] },
  "csr-fastify": { rules: ["test-policy", "ship-checklist"] },
  "csr-fastapi": { rules: ["test-policy", "ship-checklist"] },
  "ssr-htmx": { rules: ["test-policy"] },
  "ssr-nextjs": { rules: ["ship-checklist"] },
  data: { rules: ["test-policy", "ship-checklist"] },
  executive: { rules: ["git-policy"] },
  full: { rules: ["cli-development", "test-policy"] },
  // v0.5.0 — executive-style baselines (common rules only).
  "project-management": { rules: ["git-policy", "change-management"] },
  "growth-marketing": { rules: ["git-policy", "change-management"] },
};

describe("11-track install (E2E vs templates/)", () => {
  let projectDir: string;

  beforeEach(() => {
    projectDir = mkdtempSync(join(tmpdir(), "ch-11track-"));
  });

  afterEach(() => {
    rmSync(projectDir, { recursive: true, force: true });
  });

  it.each(TRACKS)("track=%s install passes core invariants", (track) => {
    const report = runInstall({
      runExternal: NO_EXTERNAL,
      harnessRoot: HARNESS_ROOT,
      projectDir,
      spec: buildSpec([track], projectDir),
    });

    // Core: skeleton + meta. 하네스 앵커는 v26.141.0(P5 · ADR-060)부터 프로젝트 루트다.
    expect(existsSync(join(projectDir, "CLAUDE-uzys-harness.md"))).toBe(true);
    expect(existsSync(join(projectDir, ".claude/settings.json"))).toBe(true);
    // Project-root CLAUDE.md — fill-in scaffold generated by mergeProjectClaude (project name +
    // active-track note + FILL sections) + 앵커 @import. Written whenever the claude baseline is installed.
    expect(existsSync(join(projectDir, "CLAUDE.md"))).toBe(true);

    // Common rules always present
    for (const rule of ["git-policy", "change-management", "doc-governance"]) {
      expect(existsSync(join(projectDir, `.claude/rules/${rule}.md`))).toBe(true);
    }

    // Per-track rules
    for (const rule of TRACK_EXPECTATIONS[track].rules) {
      expect(existsSync(join(projectDir, `.claude/rules/${rule}.md`))).toBe(true);
    }

    // .installed-tracks meta
    const meta = readFileSync(join(projectDir, ".claude/.installed-tracks"), "utf8").trim();
    expect(meta.split(/\s+/)).toContain(track);

    // .mcp.json with at least context7
    const mcp = JSON.parse(readFileSync(join(projectDir, ".mcp.json"), "utf8"));
    expect(mcp.mcpServers.context7).toBeDefined();
    for (const expected of TRACK_EXPECTATIONS[track].mcp ?? []) {
      expect(mcp.mcpServers[expected]).toBeDefined();
    }

    expect(report.installedTracks).toEqual([track]);
    expect(report.filesCopied).toBeGreaterThan(5);
  });
});

describe("track-specific skills routing", () => {
  let projectDir: string;
  beforeEach(() => {
    projectDir = mkdtempSync(join(tmpdir(), "ch-skills-"));
  });
  afterEach(() => {
    rmSync(projectDir, { recursive: true, force: true });
  });

  // #492 — 여기 있던 7종(python-* · nextjs-turbopack · investor-* · market-research)은 ECC
  // cherry-pick 이었고 함께 은퇴했다. 트랙으로 갈리는 스킬은 `ui-visual-review` 하나가 남아,
  // 같은 계약(트랙이 고르면 깔리고 아니면 안 깔린다)을 그것으로 잰다.
  it("UI 트랙은 ui-visual-review 를 깔고, 비-UI 트랙은 안 깐다", () => {
    runInstall({
      runExternal: NO_EXTERNAL,
      harnessRoot: HARNESS_ROOT,
      projectDir,
      spec: buildSpec(["ssr-nextjs"], projectDir),
    });
    expect(existsSync(join(projectDir, ".claude/skills/ui-visual-review"))).toBe(true);

    const other = mkdtempSync(join(tmpdir(), "ch-skills-data-"));
    try {
      runInstall({
        runExternal: NO_EXTERNAL,
        harnessRoot: HARNESS_ROOT,
        projectDir: other,
        spec: buildSpec(["data"], other),
      });
      expect(existsSync(join(other, ".claude/skills/ui-visual-review"))).toBe(false);
    } finally {
      rmSync(other, { recursive: true, force: true });
    }
  });

  // 은퇴한 cherry-pick 스킬이 어떤 트랙에서도 디스크에 나타나지 않는다 — 템플릿 삭제가
  // 배선까지 갔는지(설치 결과로) 본다. 목록은 카탈로그의 `RETIRED_SKILL_IDS` 에서 읽는다.
  it("은퇴한 스킬 디렉터리는 어느 트랙 설치에서도 안 생긴다 (#492)", () => {
    for (const track of ["data", "ssr-nextjs", "executive"] as const) {
      const dir = mkdtempSync(join(tmpdir(), `ch-retired-${track}-`));
      try {
        runInstall({
          runExternal: NO_EXTERNAL,
          harnessRoot: HARNESS_ROOT,
          projectDir: dir,
          spec: buildSpec([track], dir),
        });
        for (const id of RETIRED_SKILL_IDS) {
          expect(existsSync(join(dir, `.claude/skills/${id}`)), `${track}: ${id}`).toBe(false);
        }
        // 0건 함정 방지 — 같은 경로 조립으로 실재하는 것은 잡힌다.
        expect(existsSync(join(dir, ".claude/rules/git-policy.md"))).toBe(true);
      } finally {
        rmSync(dir, { recursive: true, force: true });
      }
    }
  });
});

// 2026-08-02 정비 — `--with-tauri` 룰 설치 describe 블록 삭제. `templates/rules/tauri.md` 가
//   배포에서 빠져 검사할 산출물 자체가 없다. `tauri-desktop` **자산** 선택 경로는 그대로이고
//   그쪽 커버리지는 `installer-track-matrix` / `external-assets` 가 맡는다.

describe("--cli=both produces both Claude and Codex outputs", () => {
  let projectDir: string;
  beforeEach(() => {
    projectDir = mkdtempSync(join(tmpdir(), "ch-both-"));
  });
  afterEach(() => {
    rmSync(projectDir, { recursive: true, force: true });
  });

  it("creates AGENTS.md + .codex/ alongside .claude/ (dev-method skills, no 6-Gate uzys-*)", () => {
    const report = runInstall({
      runExternal: NO_EXTERNAL,
      harnessRoot: HARNESS_ROOT,
      projectDir,
      spec: { ...buildSpec(["tooling"], projectDir), cli: ["claude", "codex"] },
    });
    expect(existsSync(join(projectDir, "CLAUDE-uzys-harness.md"))).toBe(true);
    expect(existsSync(join(projectDir, "AGENTS.md"))).toBe(true);
    expect(existsSync(join(projectDir, ".codex/config.toml"))).toBe(true);
    expect(report.codex).not.toBeNull();
    // 6-Gate workflow removed — uzys-* skills must never be generated for Codex.
    expect(report.codex?.skillFiles?.some((f) => f.includes("/uzys-"))).toBe(false);
  });

  it("codex install never emits uzys-* 6-Gate artifacts (dev-method skills only)", () => {
    const report = runInstall({
      runExternal: NO_EXTERNAL,
      harnessRoot: HARNESS_ROOT,
      projectDir,
      spec: { ...buildSpec(["tooling"], projectDir), cli: ["claude", "codex"] },
    });
    // baseline 은 그대로 생성
    expect(existsSync(join(projectDir, "AGENTS.md"))).toBe(true);
    expect(existsSync(join(projectDir, ".codex/config.toml"))).toBe(true);
    // 6-Gate workflow removed — uzys-{phase} skills / prompts must be absent.
    expect(report.codex?.skillFiles?.some((f) => f.includes("/uzys-"))).toBe(false);
    expect(existsSync(join(projectDir, ".codex/prompts"))).toBe(false);
    expect(existsSync(join(projectDir, ".agents/skills/uzys-spec"))).toBe(false);
    // 잔존 유일 번들 dev-method skill 은 native 매핑되어 존재해야 한다 (tooling = dev track).
    // 2026-08-02 정비(ADR-060)로 multi-persona-review 등은 npx 설치로 이관 — 번들 검증 표본 교체.
    expect(existsSync(join(projectDir, ".agents/skills/compaction-handoff/SKILL.md"))).toBe(true);
  });
});
